-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: ^test_data/
    -   id: autopep8-wrapper
        exclude: ^test_data/
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
        exclude: ^test_data/
-   repo: https://github.com/pre-commit/pre-commit
    sha: v0.13.3
    hooks:
    -   id: validate_config
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.1
    hooks:
    -   id: reorder-python-imports
        exclude: ^test_data/
        language_version: python2.7
